name: AristShop
version: 1.0.0
main: me.vennlmao.arisshop.ArisShop
api-version: '1.21'
folia-supported: true
authors:
  - vennlmao
depend:
  - Vault
softdepend:
  - PlaceholderAPI

commands:
  shop:
    description: Open the shop
    usage: /shop
